# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ExifRenameGUI Pipeline

on:
  push:
    branches: [main, develop, testGithubActions/**]
  pull_request:
    branches: [main, develop, testGithubActions/**]

permissions:
  contents: read
env:
  # This environment variable silences a warning triggered by running pip outside of a virtual environment. While you
  # normally shouldn't, because the scope of this is to spin a virtual machine to build the application
  PIP_ROOT_USER_ACTION: ignore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v5

      - name: Build the Exe
        # The easiest way to build a exe for windows is to use this image.
        run: docker run --volume .:/src/ --env SPECFILE=renameGUI.spec batonogov/pyinstaller-windows:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenameGUI
          path: dist/

  test:
    runs-on: ubuntu-latest

    permissions:
      # Enable writing for the checkout of the coverage history
      contents: write

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Test with pytest with coverage
        run: python -m pytest --cov --cov-report=xml
        continue-on-error: true

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        continue-on-error: true # allow lint errors, for now

      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.16
        with:
          reports: coverageReport/coverage.xml
          targetdir: coverageReport/coverageReport
          reporttypes: Html;MarkdownSummary
          sourcedirs: src
          historydir: coverageHistory

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coverageReport/coverageReport

      - name: Store Coverage History in PR Merge
        if: github.event.pull_request.merged == true
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Add Coverage History"
          file_pattern: "coverageHistory/*"

        # # - name: Setup upterm session
        # #   uses: owenthereal/action-upterm@v1
        # #   with:
        # #     limit-access-to-actor: true # Restrict to the user who triggered the workflow
        # #     limit-access-to-users: mundodisco8,joel-felcana,Joel-Skarper # Specific authorized users only
